#!/bin/bash
clear
echo "IP checker /v2.6i"
echo "----------/"
echo "ARC_dev"
echo "[1] check ip perangkat anda"
echo "[2] check ip yang ada di dalam wi-fi anda"
echo "[3] update"

read -p "silahkan pilih [1/3] " pil;
case $pil in

1)
     clear
     echo self IP
     clear
     echo "[-----------------------------]"
     echo "ip anda untuk saat ini adalah :"
     echo "[=============================]"
     echo " "
     echo " "
     read -p "[android] [linux] " pil;
   case $pil in

android)

 echo "[android]*"
 curl ifconfig.me

 


;;

linux)
  echo "linux*"
  ifconfig
;;

esac

;;
2)
  clear
  echo "______________________________________________________________________"
  echo "ip/perangkat lain yang sedang tersambung ke wifi anda saat ini adalah:"
  echo  "===================================================================="
  arp -a 

  echo " "
  echo " "

;;

3)
  echo "updating..."
  cd

  clear
  echo "menghapus instalasi lama..."
  rm -r ipchecker
  clear
  echo 'mendownload file baru...'
  git clone https://github.com/afri64/ipchecker/
  echo "menginstall file baru..."
  cd
  cd ipchecker
  bash ipchk

;;

*)
clear
  echo "silahkan pilih nomor yang ada di dalam menu"

;;


esac
