#!/bin/bash
clear
echo " /IP checker/v3.5i"
echo "/----------/"
echo "ARC_dev"
echo " "
echo ":::::::::::::::::::::::::::::::::::::::::::::"
echo "[1] check ip perangkat anda                ::"
echo "[2] check ip yang ada di dalam wi-fi anda  ::"
echo "[3] exploit ip                             ::"
echo "[4] update                                 ::"
echo "[5] reset IP checker                       ::"
echo "[6] uninstall IP chacker                   ::"
echo ":::::::::::::::::::::::::::::::::::::::::::::"


read -p "silahkan pilih [1-6] " pil;
   case $pil in

1)

     clear
     echo self IP
     clear
     echo "[-----------------------------]"
     echo "ip anda untuk saat ini adalah :"
     echo "[=============================]"
     echo " "
     echo " "
     read -p "[android] [linux] " pil;
   case $pil in

android)

 mkdir android_system_detected
 clear
 echo "[android]*"
 curl ifconfig.me
 rm -r linux.txt


 


;;

linux)
  rm -r android_system_detected
  echo "linux*"
  ifconfig
  echo "linux system detected" > linux.txt

;;

esac

;;
2)
  clear
  echo "______________________________________________________________________"
  echo "ip/perangkat lain yang sedang tersambung ke wifi anda saat ini adalah:"
  echo  "===================================================================="
  arp -a 

  echo " "
  echo " "

;;

3)

  clear
  echo "[[-[masukkan ip target]-]]"
  read ip
  apt-get install tracepath
  clear
  traceroute $ip


;;

4)
  echo "updating..."
  cd

  clear
  echo "menghapus instalasi lama..."
  rm -r ipchecker
  clear
  echo 'mendownload file baru...'
  git clone https://github.com/afri64/ipchecker/
  echo "menginstall file baru..."
  cd
  cd ipchecker
  bash ipchk

;;

5)

clear
  echo "mereset IP checker..."
  rm -r linux.txt
  rm -r android_system_detected
  clear
  echo "IP checker selesai di reset"

;;

6)

  echo uninstalling...
  cd
  cd
  rm -r ipchecker

;;

02)

clear
   echo "Itu waifu gua:V"
   echo " "
   echo " waifu lu siapa?:V"
   read waifu
   echo "CIEEE CIEEE suka ama $waifu :V"

;;


*)
clear
  echo "silahkan pilih nomor yang ada di dalam menu"

;;


esac
